Add bookings
LenaChaldina/java-shareit pull request #2
Opened 2023-02-07 00:39 UTC by LenaChaldina

2023-02-08 05:53 UTC, ErkinKasymaliev requested changes
Привет, хорошая работа!
Оставил комменты

2023-02-08 05:53 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new RequestError(HttpStatus.BAD_REQUEST, "бронь уже обработана");
тут Bad_Request не подойдет, используйте Conflict

2023-02-08 05:53 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                }
лучше так: 
if (approved) {
    booking.get().setStatus(Status.APPROVED)
} else {
    booking.get().setStatus(Status.REJECTED);
}
bookingRepository.save(booking.get());

2023-02-08 05:53 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                throw new RequestError(HttpStatus.NOT_FOUND, "Нет доступа на просмотр");
здесь вместо NOT_FOUND используйте Forbidden

2023-02-08 05:53 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                .stream().map(booking -> BookingMapper.toBookingSmallDto(booking))
тут и в других местах можно так .map(BookingMapper::toBookingSmallDto)

2023-02-08 08:28 UTC, LenaChaldina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new RequestError(HttpStatus.BAD_REQUEST, "бронь уже обработана");
done

2023-02-08 08:32 UTC, LenaChaldina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                }
done

2023-02-08 08:32 UTC, LenaChaldina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                throw new RequestError(HttpStatus.NOT_FOUND, "Нет доступа на просмотр");
done

2023-02-08 08:35 UTC, LenaChaldina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                .stream().map(booking -> BookingMapper.toBookingSmallDto(booking))
done

2023-02-08 08:41 UTC, LenaChaldina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                throw new RequestError(HttpStatus.NOT_FOUND, "Нет доступа на просмотр");
блин сорян, откатываю назад - тесты поломались(
Status code is 404 | AssertionError: expected 403 to be one of [ 404 ]
но в реальной жизни (если найду работу), буду использовать Forbidden в таком случае

2023-02-08 08:43 UTC, LenaChaldina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new RequestError(HttpStatus.BAD_REQUEST, "бронь уже обработана");
Откатываю назад, упал тест( 
Status code is 400 | AssertionError: expected 409 to be one of [ 400 ]
Но я честно попробовала.

2023-02-09 06:41 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new RequestError(HttpStatus.BAD_REQUEST, "бронь уже обработана");
ок, тесты под этот статус написаны

2023-02-09 06:45 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-03-04 15:09 UTC, merged