Add item requests
LenaChaldina/java-shareit pull request #3
Opened 2023-03-11 18:34 UTC by LenaChaldina

2023-03-16 09:08 UTC, ErkinKasymaliev requested changes
привет, хорошая работа!
Оставил пару комменто и еще: для этих эндпойнтов GET /items, GET /items/search тоже нужна пагинация

2023-03-16 09:08 UTC, ErkinKasymaliev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    void getBookingById() {
почему тесты пустые?

2023-03-16 09:08 UTC, ErkinKasymaliev commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +        assertEquals(expected, actual);
еще советую проверять verify(someRepo, times("кол-во раз сколько должен вызваться метод").someRepoMethod(); - так вы проверяете вызвался ли замоканный метод нужное вам ко-во раз

2023-03-16 09:08 UTC, ErkinKasymaliev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    BookingService bookingService;
сервиса мокать не надо - их надо инжектить, мокать надо репозитория

2023-03-16 09:08 UTC, ErkinKasymaliev commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +        verify(itemService).search(userId, "");
отлично

2023-03-17 20:27 UTC, LenaChaldina commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    void getBookingById() {
Заполнила пустые тесты. Я создала класс, написала 1 тест, хотела потом написать остальные, но забыла.

2023-03-17 20:30 UTC, LenaChaldina commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    void getBookingById() {
Пагинацию добавила.

2023-03-17 20:50 UTC, LenaChaldina commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +        assertEquals(expected, actual);
да, я так и делала в моках, а этот - интеграционный

2023-03-17 21:17 UTC, LenaChaldina commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    BookingService bookingService;
Хм, но я использую @WebMvcTest и @MockBean. В теории написано, что это упрощает написание тестов: https://practicum.yandex.ru/learn/java-developer/courses/ec5e03ed-e12f-43c5-93d1-638a79454e03/sprints/100569/topics/5358fb86-2387-40c3-825e-f52551fa4815/lessons/0e6dbee7-ce7a-4e6f-90b2-934808f6ba2e/

2023-03-18 10:09 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-03-18 10:15 UTC, merged