add-docker
LenaChaldina/java-shareit pull request #4
Opened 2023-03-25 20:42 UTC by LenaChaldina

2023-03-26 13:32 UTC, ErkinKasymaliev requested changes
привет, хорошая работа!
Оставил пару комментов

2023-03-26 13:32 UTC, ErkinKasymaliev commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<Object> patchUser(@PathVariable("id") Long userId, @RequestBody UserRequestDto userRequestDto) {
сюда @Valid добавьте

2023-03-26 13:32 UTC, ErkinKasymaliev commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
здесь даже пакета валидации не должно быть. На сервере должны остаться только проверки касаемые бд

2023-03-26 15:27 UTC, LenaChaldina commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<Object> patchUser(@PathVariable("id") Long userId, @RequestBody UserRequestDto userRequestDto) {
готово

2023-03-26 15:27 UTC, LenaChaldina commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
исправила помники

2023-03-27 09:41 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-04-02 09:29 UTC, merged